runtime: python310 # specify the python version

service: hello-app # specify the service name

instance_class: F2 # specify the instance class
entrypoint: gunicorn -b :$PORT main:app # specify the entrypoint

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  PORT: 8080

runtime_config:
  python_version: 3
